language: java

jdk:
  - oraclejdk9

matrix:
  include:
  - os: linux-ppc64le
    jdk: openjdk8

install: mvn -f gson install -DskipTests=true
script: mvn -f gson test

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
